#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "liberaforms"
name = "Liberaforms"
description.en = "Creat and manage simple web Forms"
description.fr = "Créer et gérer des formulaires web simples"

version = "4.8.0~ynh3"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://www.liberaforms.org"
admindoc = "https://docs.liberaforms.org"
code = "https://codeberg.org/LiberaForms/server"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "eu", "es", "ca", "cs", "de", "fr", "gl", "ru", "ta"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/LiberaForms/server/archive/v4.8.0.tar.gz"
    sha256 = "2e9fb8e8e6b6a4154739d0b6087ed287998a420ae67449559d7dfa5c250e2443"
    
    autoupdate.strategy = "latest_forgejo_tag"

    [resources.sources.uv]
    amd64.url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "cc0fbb42b3642125f600a55b0b095bea65cddaadb94c6ea2b6ba5d79c5825089"
    arm64.url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "8e179ca110343a17f801444ff9ef117dba56ef5fc9f6a4c9bb77b318ddba5f24"
    armhf.url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-armv7-unknown-linux-gnueabihf.tar.gz"
    armhf.sha256 = "0cad4e1b6769e48aa1e80cf639ddcc7c1bfe9ed017e95868fed185a8d818c949"
    i386.url = "https://github.com/astral-sh/uv/releases/download/0.11.0/uv-i686-unknown-linux-gnu.tar.gz"
    i386.sha256 = "59928a0267501c20d9f9942f5f1d81a991ec55e29a19e002ae3d5c178c674c89"
    
    in_subdir = true
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/astral-sh/uv"
    autoupdate.asset.amd64 = "^uv-x86_64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.arm64 = "^uv-aarch64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.armhf = "^uv-armv7-unknown-linux-gnueabihf.tar.gz$"
    autoupdate.asset.i386 = "^uv-i686-unknown-linux-gnu.tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "postgresql, python3-venv, python3-dev, gcc, libpq-dev, libcairo2, libffi-dev"

    packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "mime-support";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "media-types mailcap";
    fi
    """

    [resources.database]
    type = "postgresql"
