#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "liberaforms"
name = "Liberaforms"
description.en = "Creat and manage simple web Forms"
description.fr = "Créer et gérer des formulaires web simples"

version = "4.10.0~ynh3"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://www.liberaforms.org"
admindoc = "https://docs.liberaforms.org"
code = "https://codeberg.org/LiberaForms/server"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "eu", "es", "ca", "cs", "de", "fr", "gl", "ru", "ta"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/LiberaForms/server/archive/v4.10.0.tar.gz"
    sha256 = "e22bce07009083691f4ff70958c7d3721753456df561b9494724e3ffd20c95db"
    
    autoupdate.strategy = "latest_forgejo_tag"

    [resources.sources.uv]
    amd64.url = "https://github.com/astral-sh/uv/releases/download/0.11.29/uv-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "04f8b82f5d47f0512dcd32c67a4a6f16a0ea27c81537c338fd0ad6b23cebe829"
    arm64.url = "https://github.com/astral-sh/uv/releases/download/0.11.29/uv-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "94500fb064ae3c971a873cba64d94694c50677e0a4dbf78735c80509e7429919"
    armhf.url = "https://github.com/astral-sh/uv/releases/download/0.11.29/uv-armv7-unknown-linux-gnueabihf.tar.gz"
    armhf.sha256 = "7b5717ae304fbb1e94104699fb8c08b32d1537fedc90dd8fcf87768d818951ed"
    i386.url = "https://github.com/astral-sh/uv/releases/download/0.11.29/uv-i686-unknown-linux-gnu.tar.gz"
    i386.sha256 = "c62af324951ae6f31f9453280e077176c96b6e31897d8133c00411a91a20878f"
    
    in_subdir = true
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/astral-sh/uv"
    autoupdate.asset.amd64 = "^uv-x86_64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.arm64 = "^uv-aarch64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.armhf = "^uv-armv7-unknown-linux-gnueabihf.tar.gz$"
    autoupdate.asset.i386 = "^uv-i686-unknown-linux-gnu.tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "postgresql, python3-venv, python3-dev, gcc, libpq-dev, libcairo2, libffi-dev"

    packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "mime-support";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "media-types mailcap";
    fi
    """

    [resources.database]
    type = "postgresql"
