#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "liberaforms"
name = "Liberaforms"
description.en = "Creat and manage simple web Forms"
description.fr = "Créer et gérer des formulaires web simples"

version = "4.8.1~ynh7"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://www.liberaforms.org"
admindoc = "https://docs.liberaforms.org"
code = "https://codeberg.org/LiberaForms/server"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "eu", "es", "ca", "cs", "de", "fr", "gl", "ru", "ta"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/LiberaForms/server/archive/v4.8.1.tar.gz"
    sha256 = "a76620f87eb99dd46227d3eedb86e0da65113a157e0328bedfd7722686817148"
    
    autoupdate.strategy = "latest_forgejo_tag"

    [resources.sources.uv]
    amd64.url = "https://github.com/astral-sh/uv/releases/download/0.11.17/uv-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "0017ccecaeb4d431d7f93b583ebff0c5c38e00eb734fcf13d05f72ca419125fe"
    arm64.url = "https://github.com/astral-sh/uv/releases/download/0.11.17/uv-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "de008880a903ac2c5654647dc19a75c0d6652313c977a2bc5ce05e1e3a93429e"
    armhf.url = "https://github.com/astral-sh/uv/releases/download/0.11.17/uv-armv7-unknown-linux-gnueabihf.tar.gz"
    armhf.sha256 = "c941377b20fdd4b101376a9c8ce37c209d36655697815a32658a7cbcb3212409"
    i386.url = "https://github.com/astral-sh/uv/releases/download/0.11.17/uv-i686-unknown-linux-gnu.tar.gz"
    i386.sha256 = "89f859f3bfaf3a74733aef671e6a4ade36173623d4539d3559e11caa2c722718"
    
    in_subdir = true
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/astral-sh/uv"
    autoupdate.asset.amd64 = "^uv-x86_64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.arm64 = "^uv-aarch64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.armhf = "^uv-armv7-unknown-linux-gnueabihf.tar.gz$"
    autoupdate.asset.i386 = "^uv-i686-unknown-linux-gnu.tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "postgresql, python3-venv, python3-dev, gcc, libpq-dev, libcairo2, libffi-dev"

    packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "mime-support";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "media-types mailcap";
    fi
    """

    [resources.database]
    type = "postgresql"
